apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  url: bXlzcWwuc2VydmljZXMuY29tCg==
  username: cm9vdF91c2VyCg==
  password: RXhwZXJ0cyExMjMK 

# username: root_user
# password: Experts!123
# database: mysql.services.com

